import type { CuratedFeed } from './feedTypes';

export const CURATED_FEEDS: CuratedFeed[] = [
  {
    id: 'feodo-c2-ips',
    name: 'Feodo Tracker Botnet C2 IPs',
    description: 'Active botnet C2 IP addresses tracked by abuse.ch',
    url: 'https://feodotracker.abuse.ch/downloads/ipblocklist.csv',
    format: 'csv',
    indicatorType: 'ip',
    indicatorField: 'dst_ip',
    trustScore: 92,
    updateFrequency: 'Daily',
    category: 'C2 Infrastructure',
    source: 'abuse.ch',
  },
  {
    id: 'threatfox-ips',
    name: 'ThreatFox IPs',
    description: 'Recent malicious IP:port combinations from ThreatFox community',
    url: 'https://threatfox.abuse.ch/export/csv/ip-port/recent/',
    format: 'csv',
    indicatorType: 'ip',
    indicatorField: 'ioc_value',
    trustScore: 88,
    updateFrequency: 'Daily',
    category: 'C2 Infrastructure',
    source: 'abuse.ch',
  },
  {
    id: 'urlhaus-malicious-urls',
    name: 'URLhaus Malicious URLs',
    description: 'Recently added malicious URLs distributing malware payloads',
    url: 'https://urlhaus.abuse.ch/downloads/csv_recent/',
    format: 'csv',
    indicatorType: 'url',
    indicatorField: 'url',
    trustScore: 87,
    updateFrequency: 'Daily',
    category: 'Malware Distribution',
    source: 'abuse.ch',
  },
  {
    id: 'threatfox-domains',
    name: 'ThreatFox Domains',
    description: 'Recent malicious domains from the ThreatFox community feed',
    url: 'https://threatfox.abuse.ch/export/csv/domains/recent/',
    format: 'csv',
    indicatorType: 'domain',
    indicatorField: 'ioc_value',
    trustScore: 85,
    updateFrequency: 'Daily',
    category: 'Malware Distribution',
    source: 'abuse.ch',
  },
  {
    id: 'spamhaus-drop',
    name: 'Spamhaus DROP List',
    description: 'Networks hijacked or leased by professional spam/cybercrime operations',
    url: 'https://www.spamhaus.org/drop/drop.txt',
    format: 'plaintext',
    indicatorType: 'ip',
    indicatorField: '',
    trustScore: 95,
    updateFrequency: 'Daily',
    category: 'Blocklists',
    source: 'Spamhaus',
  },
  {
    id: 'et-compromised-ips',
    name: 'Emerging Threats Compromised IPs',
    description: 'Known compromised hosts actively participating in attacks',
    url: 'https://rules.emergingthreats.net/blockrules/compromised-ips.txt',
    format: 'plaintext',
    indicatorType: 'ip',
    indicatorField: '',
    trustScore: 82,
    updateFrequency: 'Daily',
    category: 'Blocklists',
    source: 'Emerging Threats',
  },
  {
    id: 'cisa-kev',
    name: 'CISA Known Exploited Vulnerabilities',
    description: 'CISA catalog of known exploited vulnerabilities',
    url: 'https://www.cisa.gov/sites/default/files/csv/known_exploited_vulnerabilities.csv',
    format: 'csv',
    indicatorType: 'mixed',
    indicatorField: 'cveID',
    trustScore: 95,
    updateFrequency: 'Weekly',
    category: 'Government / CERT',
    source: 'CISA',
  },
  {
    id: 'openphish-feed',
    name: 'OpenPhish Feed',
    description: 'Active phishing URLs identified by OpenPhish intelligence platform',
    url: 'https://raw.githubusercontent.com/openphish/public_feed/refs/heads/main/feed.txt',
    format: 'plaintext',
    indicatorType: 'url',
    indicatorField: '',
    trustScore: 78,
    updateFrequency: 'Daily',
    category: 'Phishing',
    source: 'OpenPhish',
  },
];

export const CURATED_CATEGORIES = [...new Set(CURATED_FEEDS.map(f => f.category))];
