import type { Provider } from './types';

export const PROVIDERS: Provider[] = [
  // ── Free / no-key providers ─────────────────────────────────────
  {
    id: 'internetdb',
    name: 'Shodan InternetDB',
    shortName: 'InternetDB',
    description: 'Free Shodan service returning open ports, CVEs, hostnames, CPEs, and tags for any IP. No key required.',
    docsUrl: 'https://internetdb.shodan.io/docs',
    supports: ['ip'],
    authType: 'none',
    keyLabel: '',
    keyPlaceholder: '',
    requiresKey: false,
    tags: ['IP', 'Ports', 'CVE', 'Scanning'],
    notes: 'Public API — no key required. Returns ports, CVEs, hostnames, CPEs, and tags.',
    tier: 'free',
    canValidate: false,
  },
  {
    id: 'nvd',
    name: 'NVD (NIST)',
    shortName: 'NVD',
    description: 'NIST National Vulnerability Database — the authoritative US government CVE and CPE repository.',
    docsUrl: 'https://nvd.nist.gov/developers/vulnerabilities',
    supports: ['cve'],
    authType: 'api-key',
    keyLabel: 'API Key',
    keyPlaceholder: 'Your NVD API key (optional)',
    requiresKey: false,
    tags: ['CVE', 'CPE', 'Vulnerabilities', 'CVSS', 'CISA KEV'],
    notes: 'Public without a key (5 req/30s). Free API key raises limit to 50 req/30s.',
    freeTierNote: 'Free key at nvd.nist.gov/developers/request-an-api-key — raises rate limit 10×.',
    tier: 'trial',
    upgradeTo: 'https://nvd.nist.gov/developers/request-an-api-key',
    canValidate: false,
    portalUrl: 'https://nvd.nist.gov/developers/request-an-api-key',
  },
  {
    id: 'whois',
    name: 'WHOIS / RDAP',
    shortName: 'WHOIS',
    description: 'Domain registration and ownership data via WHOIS protocol.',
    docsUrl: 'https://who.is/',
    supports: ['ip'],
    authType: 'none',
    keyLabel: '',
    keyPlaceholder: '',
    requiresKey: false,
    tags: ['WHOIS', 'IP', 'Registration'],
    notes: 'Public WHOIS via RDAP regional registries — no key required.',
    tier: 'free',
    canValidate: false,
  },
  {
    id: 'urlhaus',
    name: 'URLhaus',
    shortName: 'URLhaus',
    description: 'Abuse.ch project sharing malicious URLs used for malware distribution.',
    docsUrl: 'https://urlhaus-api.abuse.ch/',
    supports: ['url', 'domain', 'ip'],
    authType: 'api-key',
    keyLabel: 'Auth Key',
    keyPlaceholder: 'Your abuse.ch auth key',
    requiresKey: false,
    tags: ['URL', 'Malware', 'Domain'],
    notes: 'URL/host lookups are public. Auth key (shared with MalwareBazaar & ThreatFox) unlocks hash/payload lookups.',
    freeTierNote: 'Free account at abuse.ch — one key covers URLhaus, MalwareBazaar, and ThreatFox.',
    tier: 'community',
    upgradeTo: 'https://auth.abuse.ch/login',
    canValidate: true,
  },

  // ── Community / free-key providers ──────────────────────────────
  {
    id: 'malwarebazaar',
    name: 'MalwareBazaar',
    shortName: 'MalwareBazaar',
    description: 'Abuse.ch malware sample repository. Hash lookups return file metadata, tags, YARA hits, and download links.',
    docsUrl: 'https://bazaar.abuse.ch/api/',
    supports: ['hash'],
    authType: 'api-key',
    keyLabel: 'Auth Key',
    keyPlaceholder: 'Your abuse.ch auth key',
    requiresKey: true,
    tags: ['Hash', 'Malware', 'YARA', 'Samples'],
    notes: 'Auth key shared with URLhaus and ThreatFox.',
    freeTierNote: 'Free account at abuse.ch — one key covers URLhaus, MalwareBazaar, and ThreatFox.',
    tier: 'community',
    upgradeTo: 'https://auth.abuse.ch/login',
    canValidate: true,
  },
  {
    id: 'threatfox',
    name: 'ThreatFox',
    shortName: 'ThreatFox',
    description: 'Abuse.ch IOC database covering IPs, domains, URLs, and hashes linked to malware campaigns.',
    docsUrl: 'https://threatfox.abuse.ch/api/',
    supports: ['ip', 'domain', 'url', 'hash'],
    authType: 'api-key',
    keyLabel: 'Auth Key',
    keyPlaceholder: 'Your abuse.ch auth key',
    requiresKey: true,
    tags: ['IP', 'Domain', 'URL', 'Hash', 'IOC', 'Malware'],
    notes: 'Auth key shared with URLhaus and MalwareBazaar.',
    freeTierNote: 'Free account at abuse.ch — one key covers URLhaus, MalwareBazaar, and ThreatFox.',
    tier: 'community',
    upgradeTo: 'https://auth.abuse.ch/login',
    canValidate: true,
  },
  {
    id: 'circl',
    name: 'CIRCL',
    shortName: 'CIRCL',
    description: 'CIRCL Passive DNS, Passive SSL, and CVE search from the Computer Incident Response Center Luxembourg.',
    docsUrl: 'https://www.circl.lu/services/passive-dns/',
    supports: ['cve'],
    authType: 'basic',
    keyLabel: 'User:Password',
    keyPlaceholder: 'username:password',
    requiresKey: false,
    tags: ['Passive DNS', 'Passive SSL', 'IP', 'Domain', 'CVE', 'Vulnerabilities'],
    notes: 'CVE search is public. Passive DNS requires free registration at circl.lu.',
    tier: 'community',
    upgradeTo: 'https://www.circl.lu/contact/',
    canValidate: false,
    portalUrl: 'https://www.circl.lu/contact/',
  },
  {
    id: 'greynoise',
    name: 'GreyNoise',
    shortName: 'GreyNoise',
    description: 'Identifies internet background noise vs targeted attacks. Tags IPs as benign scanners, malicious, or unknown.',
    docsUrl: 'https://docs.greynoise.io/',
    supports: ['ip'],
    authType: 'api-key',
    keyLabel: 'API Key',
    keyPlaceholder: 'Your GreyNoise API key',
    requiresKey: false,
    tags: ['IP', 'Noise', 'Scanning', 'Reputation'],
    notes: 'Community API available without a key (limited). Paid key unlocks full context.',
    freeTierNote: 'Free API key: classification, tags, and geo. Community (no key): noise/riot flags only.',
    tier: 'community',
    upgradeTo: 'https://www.greynoise.io/plans',
    canValidate: true,
  },
  {
    id: 'abuseipdb',
    name: 'AbuseIPDB',
    shortName: 'AbuseIPDB',
    description: 'Community-driven IP abuse reports database. Reports malicious IPs used in hacking, spam, DDoS and more.',
    docsUrl: 'https://www.abuseipdb.com/api.html',
    supports: ['ip'],
    authType: 'api-key',
    keyLabel: 'API Key',
    keyPlaceholder: 'Your AbuseIPDB API key',
    requiresKey: true,
    tags: ['IP', 'Abuse Reports', 'Reputation'],
    freeTierNote: 'Free tier: 1,000 checks/day, 90-day max age.',
    tier: 'community',
    upgradeTo: 'https://www.abuseipdb.com/pricing',
    canValidate: true,
  },
  {
    id: 'spamhaus',
    name: 'Spamhaus DQS',
    shortName: 'Spamhaus',
    description: 'Spamhaus Data Query Service — real-time IP and domain blocklist lookups across SBL, XBL, PBL, DBL, and ZRD.',
    docsUrl: 'https://docs.spamhaus.com/datasets/docs/source/90-additional-information/DQS/010-getting-started.html',
    supports: ['ip', 'domain'],
    authType: 'api-key',
    keyLabel: 'DQS Key',
    keyPlaceholder: 'Your Spamhaus DQS key',
    requiresKey: true,
    tags: ['IP', 'Domain', 'Blocklist', 'Spam'],
    freeTierNote: 'Free DQS key available at spamhaus.com for non-commercial use.',
    tier: 'community',
    upgradeTo: 'https://www.spamhaus.com/product/data-query-service/',
    canValidate: false,
    portalUrl: 'https://portal.spamhaus.com/',
  },

  // ── Trial / freemium providers ───────────────────────────────────
  {
    id: 'virustotal',
    name: 'VirusTotal',
    shortName: 'VirusTotal',
    description: '70+ antivirus engines plus URL/domain/IP reputation and file analysis.',
    docsUrl: 'https://developers.virustotal.com/reference',
    supports: ['ip', 'domain', 'url', 'hash', 'file'],
    authType: 'api-key',
    keyLabel: 'API Key',
    keyPlaceholder: 'Your VirusTotal API key',
    requiresKey: true,
    tags: ['IP', 'Domain', 'URL', 'Hash', 'Antivirus', 'Sandbox'],
    freeTierNote: 'Free tier: 4 requests/min, 500/day. No livehunt, no retrohunt, limited file downloads.',
    tier: 'trial',
    upgradeTo: 'https://www.virustotal.com/gui/sign-in',
    canValidate: true,
    enterpriseTypes: ['file'],
  },
  {
    id: 'shodan',
    name: 'Shodan',
    shortName: 'Shodan',
    description: 'Search engine for internet-connected devices. Exposes open ports, services, banners, and vulnerabilities.',
    docsUrl: 'https://developer.shodan.io/api',
    supports: ['ip', 'domain'],
    authType: 'api-key',
    keyLabel: 'API Key',
    keyPlaceholder: 'Your Shodan API key',
    requiresKey: true,
    tags: ['IP', 'Domain', 'Ports', 'Services', 'Scanning'],
    freeTierNote: 'Free account: host lookups require a paid plan. Only search/query credits included.',
    tier: 'trial',
    enterpriseTypes: ['domain'],
    upgradeTo: 'https://account.shodan.io/billing',
    canValidate: true,
  },
  {
    id: 'censys',
    name: 'Censys',
    shortName: 'Censys',
    description: 'Internet-wide scan data for hosts, certificates, and domains. Reveals exposed services and infrastructure.',
    docsUrl: 'https://search.censys.io/api',
    supports: ['ip', 'domain'],
    authType: 'basic',
    keyLabel: 'API ID:Secret',
    keyPlaceholder: 'api_id:api_secret',
    requiresKey: true,
    tags: ['IP', 'Domain', 'Certificates', 'Scanning'],
    freeTierNote: 'Free tier: limited to 250 queries/month.',
    tier: 'trial',
    upgradeTo: 'https://censys.io/pricing',
    canValidate: true,
  },
  {
    id: 'hybrid-analysis',
    name: 'Hybrid Analysis',
    shortName: 'Hybrid Analysis',
    description: 'Free malware analysis service powered by CrowdStrike Falcon Sandbox. Supports hash, URL, and file lookups.',
    docsUrl: 'https://www.hybrid-analysis.com/docs/api/v2',
    supports: ['hash', 'url', 'domain', 'ip', 'file'],
    authType: 'api-key',
    keyLabel: 'API Key',
    keyPlaceholder: 'Your Hybrid Analysis API key',
    requiresKey: true,
    tags: ['Hash', 'Malware', 'Sandbox', 'URL'],
    freeTierNote: 'Free tier: public submissions only, no private file analysis.',
    tier: 'trial',
    upgradeTo: 'https://www.hybrid-analysis.com/apikeys/info',
    canValidate: true,
  },
  {
    id: 'malshare',
    name: 'MalShare',
    shortName: 'MalShare',
    description: 'Free malware repository providing hash lookups and sample downloads for security researchers.',
    docsUrl: 'https://malshare.com/doc.php',
    supports: ['hash'],
    authType: 'api-key',
    keyLabel: 'API Key',
    keyPlaceholder: 'Your MalShare API key',
    requiresKey: true,
    tags: ['Hash', 'Malware', 'Samples'],
    freeTierNote: 'Free tier: hash lookups and sample downloads, no bulk access.',
    tier: 'trial',
    upgradeTo: 'https://malshare.com/register.php',
    canValidate: false,
    portalUrl: 'https://malshare.com/user.php',
  },
  {
    id: 'ipqs',
    name: 'IPQualityScore',
    shortName: 'IPQS',
    description: 'Fraud detection and threat intelligence covering IP proxy/VPN/Tor detection, malicious URL scanning, and fraud scoring.',
    docsUrl: 'https://www.ipqualityscore.com/documentation/proxy-detection-api/overview',
    supports: ['ip', 'url', 'domain'],
    authType: 'api-key',
    keyLabel: 'API Key',
    keyPlaceholder: 'Your IPQS API key',
    requiresKey: true,
    tags: ['IP', 'VPN', 'Proxy', 'Tor', 'URL', 'Domain', 'Phishing', 'Fraud'],
    freeTierNote: 'Free tier: 5,000 requests/month. Paid plans unlock higher limits and additional APIs.',
    tier: 'trial',
    upgradeTo: 'https://www.ipqualityscore.com/create-account',
    canValidate: false,
    portalUrl: 'https://www.ipqualityscore.com/user/settings',
  },
  {
    id: 'apivoid',
    name: 'APIvoid',
    shortName: 'APIvoid',
    description: 'Multi-service threat intelligence covering IP reputation, domain reputation, URL analysis, SSL info, domain age, and DNS lookups. 70+ blacklist engines.',
    docsUrl: 'https://docs.apivoid.com/',
    supports: ['ip', 'domain', 'url'],
    authType: 'api-key',
    keyLabel: 'API Key',
    keyPlaceholder: 'Your APIvoid API key',
    requiresKey: true,
    tags: ['IP', 'Domain', 'URL', 'Blacklist', 'Reputation', 'SSL', 'DNS'],
    freeTierNote: 'Credits-based pricing. IP/domain: 1 credit each. URL: 5 credits. Credits deducted only on success.',
    tier: 'trial',
    upgradeTo: 'https://www.apivoid.com/pricing/',
    canValidate: false,
    portalUrl: 'https://app.apivoid.com/',
  },
  {
    id: 'maxmind',
    name: 'MaxMind GeoIP2',
    shortName: 'MaxMind',
    description: 'Paid MaxMind GeoIP2 web service — city, country, ISP, connection type, and more. Uses geoip.maxmind.com.',
    docsUrl: 'https://dev.maxmind.com/geoip/docs/web-services',
    supports: ['ip'],
    authType: 'basic',
    keyLabel: 'Account ID:License Key',
    keyPlaceholder: 'account_id:license_key',
    requiresKey: true,
    tags: ['IP', 'Geolocation', 'ISP'],
    tier: 'enterprise',
    upgradeTo: 'https://www.maxmind.com/en/geoip2-services-and-databases',
    canValidate: false,
    portalUrl: 'https://www.maxmind.com/en/account',
  },
  {
    id: 'maxmind-free',
    name: 'MaxMind GeoLite2 (Free)',
    shortName: 'GeoLite2',
    description: 'Free MaxMind GeoLite2 web service — city and country geolocation. Requires a free MaxMind account. Uses geolite.info.',
    docsUrl: 'https://dev.maxmind.com/geoip/docs/web-services',
    supports: ['ip'],
    authType: 'basic',
    keyLabel: 'Account ID:License Key',
    keyPlaceholder: 'account_id:license_key',
    requiresKey: true,
    tags: ['IP', 'Geolocation'],
    tier: 'free',
    canValidate: false,
    portalUrl: 'https://www.maxmind.com/en/account',
  },
  {
    id: 'virusbay',
    name: 'VirusBay',
    shortName: 'VirusBay',
    description: 'Community malware repository and sample sharing platform.',
    docsUrl: 'https://virusbay.io/',
    supports: ['hash'],
    authType: 'api-key',
    keyLabel: 'API Key',
    keyPlaceholder: 'Your VirusBay API key',
    requiresKey: true,
    tags: ['Hash', 'Malware', 'Community'],
    tier: 'trial',
    canValidate: false,
    portalUrl: 'https://virusbay.io/',
  },

  // ── Enterprise providers ─────────────────────────────────────────
  {
    id: 'crowdstrike',
    name: 'CrowdStrike Falcon',
    shortName: 'CrowdStrike',
    description: 'CrowdStrike Falcon Intelligence threat data including indicators, threat actors, and reports.',
    docsUrl: 'https://falcon.crowdstrike.com/documentation/page/a2a7fc0e/crowdstrike-oauth2-based-apis',
    supports: ['ip', 'domain', 'hash', 'threat-group'],
    authType: 'api-key',
    keyLabel: 'Client ID:Secret',
    keyPlaceholder: 'client_id:client_secret',
    requiresKey: true,
    tags: ['Threat Intel', 'Indicators', 'Threat Groups', 'Hash'],
    tier: 'enterprise',
    canValidate: false,
    portalUrl: 'https://falcon.crowdstrike.com/',
  },
  {
    id: 'flashpoint',
    name: 'Flashpoint',
    shortName: 'Flashpoint',
    description: 'Deep and dark web intelligence, compromised credentials, threat actor tracking.',
    docsUrl: 'https://docs.flashpoint.io/',
    supports: ['ip', 'domain', 'hash', 'threat-group'],
    authType: 'api-key',
    keyLabel: 'API Key',
    keyPlaceholder: 'Your Flashpoint API key',
    requiresKey: true,
    tags: ['Dark Web', 'Threat Actors', 'Credentials'],
    tier: 'enterprise',
    canValidate: false,
    portalUrl: 'https://fp.tools/',
  },
  {
    id: 'farsight',
    name: 'Farsight Security DNSDB',
    shortName: 'Farsight',
    description: 'Passive DNS database with historical DNS resolution data. Industry-leading coverage and retention.',
    docsUrl: 'https://docs.dnsdb.info/',
    supports: ['ip', 'domain'],
    authType: 'api-key',
    keyLabel: 'API Key',
    keyPlaceholder: 'Your Farsight DNSDB API key',
    requiresKey: true,
    tags: ['Passive DNS', 'IP', 'Domain', 'Historical'],
    tier: 'enterprise',
    canValidate: false,
    portalUrl: 'https://info.dnsdb.info/',
  },
  {
    id: 'honeydb',
    name: 'HoneyDB',
    shortName: 'HoneyDB',
    description: 'Honeypot sensor network data tracking malicious IPs and their activity patterns.',
    docsUrl: 'https://honeydb.io/api',
    supports: ['ip'],
    authType: 'api-key',
    keyLabel: 'API ID:Key',
    keyPlaceholder: 'api_id:api_key',
    requiresKey: true,
    tags: ['IP', 'Honeypot', 'Threat Intel'],
    tier: 'enterprise',
    canValidate: false,
    portalUrl: 'https://honeydb.io/',
  },
  {
    id: 'lookingglass',
    name: 'LookingGlass',
    shortName: 'LookingGlass',
    description: 'Global threat intelligence with network-level visibility into IP and domain reputation.',
    docsUrl: 'https://lookingglass.com/',
    supports: ['ip', 'domain'],
    authType: 'api-key',
    keyLabel: 'API Key',
    keyPlaceholder: 'Your LookingGlass API key',
    requiresKey: true,
    tags: ['IP', 'Domain', 'Reputation', 'Threat Intel'],
    tier: 'enterprise',
    canValidate: false,
    portalUrl: 'https://lookingglass.com/',
  },
  {
    id: 'mandiant',
    name: 'Mandiant Advantage',
    shortName: 'Mandiant',
    description: 'Mandiant threat intelligence covering threat actors, malware families, and indicators of compromise.',
    docsUrl: 'https://docs.mandiant.com/',
    supports: ['ip', 'domain', 'hash', 'threat-group'],
    authType: 'basic',
    keyLabel: 'Public Key:Private Key',
    keyPlaceholder: 'public_key:private_key',
    requiresKey: true,
    tags: ['Threat Intel', 'Threat Groups', 'Indicators', 'Malware'],
    tier: 'enterprise',
    canValidate: false,
    portalUrl: 'https://advantage.mandiant.com/',
  },
  {
    id: 'nextron',
    name: 'Nextron THOR',
    shortName: 'Nextron',
    description: 'Nextron Systems threat intelligence for IOCs, YARA rules, and compromise indicators.',
    docsUrl: 'https://www.nextron-systems.com/',
    supports: ['hash', 'ip', 'domain'],
    authType: 'api-key',
    keyLabel: 'API Key',
    keyPlaceholder: 'Your Nextron API key',
    requiresKey: true,
    tags: ['Hash', 'YARA', 'IOC', 'Threat Intel'],
    tier: 'enterprise',
    canValidate: false,
    portalUrl: 'https://www.nextron-systems.com/',
  },
  {
    id: 'spur',
    name: 'Spur',
    shortName: 'Spur',
    description: 'IP context including VPN/proxy/residential proxy detection and anonymous infrastructure mapping.',
    docsUrl: 'https://spur.us/app/docs',
    supports: ['ip'],
    authType: 'api-key',
    keyLabel: 'API Key',
    keyPlaceholder: 'Your Spur API key',
    requiresKey: true,
    tags: ['IP', 'VPN', 'Proxy', 'Anonymization'],
    tier: 'enterprise',
    canValidate: false,
    portalUrl: 'https://spur.us/',
  },
  {
    id: 'augury',
    name: 'Augury Netflow',
    shortName: 'Augury',
    description: 'Team Cymru Augury platform providing netflow and passive DNS telemetry at scale.',
    docsUrl: 'https://www.team-cymru.com/augury',
    supports: ['ip', 'domain'],
    authType: 'api-key',
    keyLabel: 'API Key',
    keyPlaceholder: 'Your Augury API key',
    requiresKey: true,
    tags: ['Netflow', 'Passive DNS', 'IP', 'Domain'],
    notes: 'Restricted access — requires Team Cymru subscription.',
    tier: 'enterprise',
    canValidate: false,
    portalUrl: 'https://www.team-cymru.com/',
  },
  {
    id: 'cyber-watchfloor',
    name: 'Cyber Watchfloor Passive DNS',
    shortName: 'Watchfloor',
    description: 'Passive DNS telemetry from Cyber Watchfloor for historical resolution tracking.',
    docsUrl: '',
    supports: ['ip', 'domain'],
    authType: 'api-key',
    keyLabel: 'API Key',
    keyPlaceholder: 'Your Watchfloor API key',
    requiresKey: true,
    tags: ['Passive DNS', 'IP', 'Domain'],
    notes: 'Restricted access — manual key entry required.',
    tier: 'enterprise',
    canValidate: false,
  },
  {
    id: 'domaintools',
    name: 'DomainTools',
    shortName: 'DomainTools',
    description: 'WHOIS, DNS, and domain history intelligence. Iris Investigate for domain profiling.',
    docsUrl: 'https://www.domaintools.com/resources/api-documentation/',
    supports: ['domain', 'ip'],
    authType: 'basic',
    keyLabel: 'Username:API Key',
    keyPlaceholder: 'username:api_key',
    requiresKey: true,
    tags: ['WHOIS', 'Domain', 'DNS', 'IP', 'History'],
    notes: 'Requires paid subscription.',
    tier: 'enterprise',
    canValidate: false,
    portalUrl: 'https://account.domaintools.com/',
  },
  {
    id: 'packet-forensics',
    name: 'Packet Forensics',
    shortName: 'Pkt Forensics',
    description: 'Passive traffic analysis and metadata collection for network forensics.',
    docsUrl: '',
    supports: ['ip', 'domain'],
    authType: 'api-key',
    keyLabel: 'API Key',
    keyPlaceholder: 'Your Packet Forensics API key',
    requiresKey: true,
    tags: ['Passive DNS', 'Network', 'IP'],
    notes: 'Restricted access — contact vendor directly.',
    tier: 'enterprise',
    canValidate: false,
  },
  {
    id: 'otx',
    name: 'AlienVault OTX',
    shortName: 'OTX',
    description: 'Open Threat Exchange — community-driven threat intelligence with pulse data, malware families, and indicator reputation for IP, domain, hash, and URL.',
    docsUrl: 'https://otx.alienvault.com/api',
    supports: ['ip', 'domain', 'hash', 'url'],
    authType: 'api-key',
    keyLabel: 'OTX API Key',
    keyPlaceholder: 'Your OTX API key',
    requiresKey: true,
    tags: ['Reputation', 'Malware', 'Pulses', 'IP', 'Domain', 'Hash'],
    tier: 'free',
    canValidate: false,
    portalUrl: 'https://otx.alienvault.com/settings',
  },
  {
    id: 'ipinfo',
    name: 'IPinfo',
    shortName: 'IPinfo',
    description: 'IP geolocation, ASN, and network data. Free tier provides country and ASN; paid adds city, carrier, privacy detection, and abuse contact.',
    docsUrl: 'https://ipinfo.io/developers',
    supports: ['ip'],
    authType: 'api-key',
    keyLabel: 'API Token',
    keyPlaceholder: 'Your IPinfo token',
    requiresKey: true,
    tags: ['IP', 'Geolocation', 'ASN', 'Carrier'],
    tier: 'free',
    canValidate: true,
    portalUrl: 'https://ipinfo.io/account',
  },
  {
    id: 'pulsedive',
    name: 'Pulsedive',
    shortName: 'Pulsedive',
    description: 'Community threat intelligence platform with risk scoring, threat feed associations, passive DNS, and enriched indicator attributes.',
    docsUrl: 'https://pulsedive.com/api/',
    supports: ['ip', 'domain', 'hash', 'url'],
    authType: 'api-key',
    keyLabel: 'API Key',
    keyPlaceholder: 'Your Pulsedive API key',
    requiresKey: true,
    tags: ['Reputation', 'Threat Feeds', 'Passive DNS', 'Risk Score'],
    tier: 'community',
    canValidate: false,
    portalUrl: 'https://pulsedive.com/account/',
  },
  {
    id: 'recordedfuture',
    name: 'Recorded Future',
    shortName: 'Rec Future',
    description: 'Enterprise threat intelligence with risk scores, evidence trails, threat actor associations, and malware context for IP, domain, hash, and URL.',
    docsUrl: 'https://docs.recordedfuture.com',
    supports: ['ip', 'domain', 'hash', 'url'],
    authType: 'api-key',
    keyLabel: 'RF Token',
    keyPlaceholder: 'Your Recorded Future API token',
    requiresKey: true,
    tags: ['Reputation', 'Risk Score', 'Threat Actors', 'Malware', 'IP', 'Domain', 'Hash'],
    tier: 'enterprise',
    canValidate: false,
    portalUrl: 'https://app.recordedfuture.com',
  },
  {
    id: 'mitre-attack',
    name: 'MITRE ATT&CK',
    shortName: 'MITRE',
    description: 'MITRE ATT&CK Enterprise knowledge base — authoritative threat group profiles with ATT&CK IDs, aliases, descriptions, and attribution context. No key required.',
    docsUrl: 'https://attack.mitre.org/groups/',
    supports: ['threat-group'],
    authType: 'none',
    keyLabel: '',
    keyPlaceholder: '',
    requiresKey: false,
    tags: ['Threat Groups', 'ATT&CK', 'Aliases', 'Attribution'],
    notes: 'Public TAXII 2.1 server — no key required. Full group catalogue fetched once and cached per session.',
    tier: 'free',
    canValidate: false,
  },
];

export const TIER_LABELS: Record<string, string> = {
  free:       'Free',
  community:  'Community',
  trial:      'Trial / Freemium',
  enterprise: 'Enterprise',
};

export const TIER_ORDER = ['free', 'community', 'trial', 'enterprise'] as const;

export function getProvider(id: string): Provider | undefined {
  return PROVIDERS.find(p => p.id === id);
}

export function supportingProviders(artifactType: string): Provider[] {
  return PROVIDERS.filter(p => p.supports.includes(artifactType as never));
}

export function routedProviders(
  artifactType: string,
  prefs: import('./types').RoutingPrefs
): import('./types').Provider[] {
  return PROVIDERS.filter(p => {
    if (!p.supports.includes(artifactType as never)) return false;
    const providerPrefs = prefs[p.id];
    if (!providerPrefs) return true;
    const val = providerPrefs[artifactType as import('./types').ArtifactType];
    return val === undefined ? true : val;
  });
}
